### ISSUE TITLE
CodeChef parser is broken

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#49]
``` console
$ oj -v d -n 'https://www.codechef.com/PLIN2020/problems/CNTSET'              
[DEBUG] args: Namespace(cookie=PosixPath('/home/ubuntu/.local/share/online-judge-tools/cookie.jar'), directory=None, dry_run=True, format=None, json=False, silent=False, subcommand='d', system=False, url='https://www.codechef.com/PLIN2020/problems/CNTSET', verbose=True, version=False, yukicoder_token=None)
[DEBUG] User-Agent: online-judge-tools/10.0.3 (+https://github.com/online-judge-tools/oj)
[DEBUG] 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge_command/main.py", line 227, in main
    run_program(namespace, parser=parser)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge_command/main.py", line 202, in run_program
    download(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/download.py", line 47, in download
    samples = problem.download_sample_cases(session=sess)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/codechef.py", line 59, in download_sample_cases
    raise SampleParseError('no markdown')
onlinejudge_workaround_for_conflict.type.SampleParseError: no markdown

[ERROR] no markdown
$ oj --version
online-judge-tools 10.0.3 (+ online-judge-api-client 10.0.8)
```

**Comment by kmyk** [comment]
The module is disabled at https://github.com/online-judge-tools/api-client/pull/50
