### ISSUE TITLE
Downloading from Facebook doesn't work

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#84]
## Description

The platform is updated and this brakes our program.
The new URLs are like https://www.facebook.com/codingcompetitions/hacker-cup/2020/qualification-round/problems/A

Also, now the old URLs like https://www.facebook.com/hackercup/problem/448364075989193/ are unavailable (without appropriate redirection).

## Error log

``` console
$ oj d https://www.facebook.com/codingcompetitions/hacker-cup/2020/qualification-round/problems/A
[INFO] online-judge-tools 10.0.5 (+ online-judge-api-client 10.2.5)
[INFO] unknown problem: https://www.facebook.com/codingcompetitions/hacker-cup/2020/qualification-round/problems/A
[ERROR] The contest "https://www.facebook.com/codingcompetitions/hacker-cup/2020/qualification-round/problems/A" is not supported
Traceback (most recent call last):
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/main.py", line 242, in main
    run_program(parsed, parser=parser)
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/main.py", line 208, in run_program
    download(args)
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/subcommand/download.py", line 36, in download
    raise requests.exceptions.InvalidURL('The contest "%s" is not supported' % args.url)
requests.exceptions.InvalidURL: The contest "https://www.facebook.com/codingcompetitions/hacker-cup/2020/qualification-round/problems/A" is not supported
```

**Comment by kmyk** [comment]
The test is disabled at https://github.com/online-judge-tools/api-client/pull/85

**Comment by kmyk** [comment]
``` console
$ curl https://www.facebook.com/api/graphql/ --data-raw 'fb_api_caller_class=RelayModern&fb_api_req_friendly_name=CodingCompetitionsContestRootQuery&variables=%7B%22series_vanity%22%3A%22hacker-cup%22%2C%22season_vanity%22%3A%222020%22%2C%22contest_vanity%22%3A%22round-1%22%7D&doc_id=2709858395781426' | jq .data.contestSeries.contestSeason.contest.id
1380758198768948
$ curl 'https://www.facebook.com/api/graphql/' --data-raw 'fb_api_caller_class=RelayModern&fb_api_req_friendly_name=CodingCompetitionsContestProblemQuery&variables=%7B%22contest_id%22%3A%221380758198768948%22%2C%22series_vanity%22%3A%22hacker-cup%22%2C%22display_index%22%3A%22C%22%2C%22participation_type%22%3A%22UNTIMED_PRACTICE%22%2C%22can_submit%22%3Afalse%7D&doc_id=3556774947707941' | jq .data.contest.problem.problem_sample_test_case_set
{
  "full_input_download_uri": "https://www.facebook.com/async/codingproblems/download/full-batch/?test_case_set_id=285637029391998&download_type=INPUT",
  "full_output_download_uri": "https://www.facebook.com/async/codingproblems/download/full-batch/?test_case_set_id=285637029391998&download_type=OUTPUT",
  "test_case_set_full_input": "6\n3 2\n***\n1 2\n0 0 0\n3 2\n###\n1 2\n0 0 0\n3 2\n#**\n1 1\n0 0 0\n6 5\n*#***#\n1 1 2 2 3\n0 0 0\n5 4\n**##*\n1 1 2 2\n0 0 0\n10 2\n**#*#***#*\n1 2\n3 4 5\n",
  "test_case_set_full_output": "Case #1: 3 4\nCase #2: 0 4\nCase #3: 1 2\nCase #4: 3 8\nCase #5: 3 12\nCase #6: 15 16\n",
  "id": "285637029391998"
}
```

`*_vanity` are in the URL. `doc_id` seems fixed value.
