### ISSUE TITLE
For Admin, memory Limit Parsing of AtCoder is broken

### ISSUE THREAD

**Issue by yosupo06** [online-judge-tools/api-client#90]
## Description

AtCoderのadmin権限を持っている問題に対し、service.atcoder.AtCoderProblem.get_available_languages()を呼ぶと以下のエラーで落ちます。Time Limit / Memory Limitの後ろに"Edit Task"が生まれ、パースが壊れるからです。

直す場合は https://github.com/yosupo06/api-client/commit/7a6348938fe2f3913bbf0f91637806f5c9b8fc92 のようにすると直るはずです。(現状だと`memory_limit.endswith(' MB')`が動かなくなる。)

バグの性質上 (対象者が狭い && テスト不可能) なのですが、対応する価値がありそうならば↑の修正をpull requestで送るつもりです。

## Error log

``` console
Traceback (most recent call last):
  File "run_test.py", line 99, in <module>
    atcoder_test(source, problem)
  File "run_test.py", line 72, in atcoder_test
    atcoder_lang = problem.get_available_languages()
  File "/usr/local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 877, in get_available_languages
    data = self.download_data(session=session)
  File "/usr/local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 812, in download_data
    return AtCoderProblemDetailedData.from_html(html, problem=self, session=session, response=resp, timestamp=timestamp)
  File "/usr/local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 771, in from_html
    data = AtCoderProblemData._from_html(html, problem=problem, session=session, response=response, timestamp=timestamp)
  File "/usr/local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 592, in _from_html
    assert False
```

## Other notes

-   Will you try to create a pull request?
    -   yes

**Comment by kmyk** [comment]
これは対応する価値はあるのでぜひプルリクしてほしい
(そういう問題があるとは聞いてたのですが、私にはそもそも実装不可能なので諦めていました)

**Comment by kmyk** [comment]
(ところで弁解なのですが、こういう「すこしでも壊れてたら積極的にエラーにしていく」という方針の実装はユーザ数がすくなかった時期の名残りです。以前はほぼ誰もバグ報告をしてくれなかったので、下手にエラーから回復してると「壊れてるけどだいたい動くしええやろｗ」されてしまって壊れたままずっと機能してないみたいなのが多かった。最近はユーザもテストも十分揃ってきたので、今後はあまりこういうことでは落ちないようにしていくつもりです。:bow:)
